# Generated by Django 5.2.7 on 2026-02-24 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('location_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='spots/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chocolatin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('image_uncut', models.ImageField(blank=True, null=True, upload_to='chocs/images/')),
                ('image_cut', models.ImageField(blank=True, null=True, upload_to='chocs/images/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chocolatins', to='base.spot')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
