# Generated by Django 5.2.7 on 2026-02-24 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChocolatinScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('m2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('m3', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('c1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('c2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('o', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('p', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('r', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('t', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('chocolatin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chocolatin_score', to='base.chocolatin')),
            ],
        ),
    ]
