# Generated by Django 5.2.7 on 2026-03-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_chocolatinscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
